version: '3.8'

services:
  app:
    build: .
    container_name: musiconnect-app
    ports:
      - "8085:8081"  # Tu máquina:contenedor
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musiconnect_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    container_name: musiconnect-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: musiconnect_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
